/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homenya_penjual;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import kelas_java.OBJ_produk;
import kelas_java.db_connection;

/**
 *
 * @author ASUS
 */
@WebServlet(name = "seller_kotakMasuk_ditolak", urlPatterns = {"/seller_kotakMasuk_ditolak"})
public class seller_kotakMasuk_ditolak extends HttpServlet {

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        PrintWriter out = response.getWriter();
        String levelAkun = null;
        String idAkun = null;

        Cookie[] cookies = request.getCookies();
        if (cookies != null) {
            for (Cookie cookie : cookies) {
                if (cookie.getName().equals("levelAkun")) {
                    levelAkun = cookie.getValue();
                }
                if (cookie.getName().equals("idAkun")) {
                    idAkun = cookie.getValue();
                }
            }
            if (levelAkun.equals("seller")) {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = db_connection.connect_to_Db();

                    PreparedStatement ps = conn.prepareStatement("SELECT * FROM tabel_kotak_masuk WHERE request_ke=? AND status_request = 'ditolak' ");
                    ps.setString(1, idAkun);

                    ResultSet rs = ps.executeQuery();
                    ArrayList<OBJ_produk> products = new ArrayList<OBJ_produk>();
                    while (rs.next()) {
                        OBJ_produk produk_req = new OBJ_produk();

                        produk_req.setId_produk(rs.getString("id_request"));
                        produk_req.setNama_produk(rs.getString("nama_barang_request"));

                        products.add(produk_req);
                    }

                    try {
                        out.println("<!DOCTYPE html>\n"
                                + "<html lang=\"en\" >\n"
                                + "    <head>\n"
                                + "        <meta charset=\"UTF-8\">\n"
                                + "        <title>Dashboard Toko</title>\n"
                                + "        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\n"
                                + "        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>\n"
                                + "        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n"
                                + "        <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\n"
                                + "        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">"
                                + "        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n"
                                + "        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>"
                                + "        <style type=\"text/css\">\n"
                                + "            @import url('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css');\n"
                                + "            @font-face {\n"
                                + "                font-family: 'Lato';\n"
                                + "                font-style: normal;\n"
                                + "                font-weight: 300;\n"
                                + "                src: local('Lato Light'), local('Lato-Light'), url(https://fonts.gstatic.com/s/lato/v16/S6u9w4BMUTPHh7USSwiPHA.ttf) format('truetype');\n"
                                + "            }\n"
                                + "            @font-face {\n"
                                + "                font-family: 'Lato';\n"
                                + "                font-style: normal;\n"
                                + "                font-weight: 400;\n"
                                + "                src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v16/S6uyw4BMUTPHjx4wWw.ttf) format('truetype');\n"
                                + "            }\n"
                                + "            @font-face {\n"
                                + "                font-family: 'Lato';\n"
                                + "                font-style: normal;\n"
                                + "                font-weight: 700;\n"
                                + "                src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v16/S6u9w4BMUTPHh6UVSwiPHA.ttf) format('truetype');\n"
                                + "            }\n"
                                + "            *,\n"
                                + "            *:before,\n"
                                + "            *:after {\n"
                                + "                -webkit-box-sizing: border-box;\n"
                                + "                -moz-box-sizing: border-box;\n"
                                + "                box-sizing: border-box;\n"
                                + "            }\n"
                                + "            body {\n"
                                + "                background: #f5f5f5;\n"
                                + "                padding: 0;\n"
                                + "                margin: 0;\n"
                                + "                font-family: 'Lato', sans-serif;\n"
                                + "            }\n"
                                + "            i.fa {\n"
                                + "                font-size: 16px;\n"
                                + "            }\n"
                                + "            p {\n"
                                + "                font-size: 16px;\n"
                                + "                line-height: 1.42857143;\n"
                                + "            }\n"
                                + "            .header {\n"
                                + "                position: fixed;\n"
                                + "                z-index: 10;\n"
                                + "                top: 0;\n"
                                + "                left: 0;\n"
                                + "                background: #F2849E;\n"
                                + "                width: 100%;\n"
                                + "                height: 50px;\n"
                                + "                line-height: 50px;\n"
                                + "                color: #fff;\n"
                                + "            }\n"
                                + "            .header .logo {\n"
                                + "                text-transform: uppercase;\n"
                                + "                letter-spacing: 1px;\n"
                                + "            }\n"
                                + "            .header #menu-action {\n"
                                + "                display: block;\n"
                                + "                float: left;\n"
                                + "                width: 60px;\n"
                                + "                height: 50px;\n"
                                + "                line-height: 50px;\n"
                                + "                margin-right: 15px;\n"
                                + "                color: #fff;\n"
                                + "                text-decoration: none;\n"
                                + "                text-align: center;\n"
                                + "                background: rgba(0, 0, 0, 0.15);\n"
                                + "                font-size: 13px;\n"
                                + "                text-transform: uppercase;\n"
                                + "                letter-spacing: 1px;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .header #menu-action i {\n"
                                + "                display: inline-block;\n"
                                + "                margin: 0 5px;\n"
                                + "            }\n"
                                + "            .header #menu-action span {\n"
                                + "                width: 0px;\n"
                                + "                display: none;\n"
                                + "                overflow: hidden;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .header #menu-action:hover {\n"
                                + "                background: rgba(0, 0, 0, 0.25);\n"
                                + "            }\n"
                                + "            .header #menu-action.active {\n"
                                + "                width: 250px;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .header #menu-action.active span {\n"
                                + "                display: inline;\n"
                                + "                width: auto;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .sidebar {\n"
                                + "                position: fixed;\n"
                                + "                z-index: 10;\n"
                                + "                left: 0;\n"
                                + "                top: 50px;\n"
                                + "                height: 100%;\n"
                                + "                width: 60px;\n"
                                + "                background: #fff;\n"
                                + "                border-right: 1px solid #ddd;\n"
                                + "                text-align: center;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .sidebar:hover,\n"
                                + "            .sidebar.active,\n"
                                + "            .sidebar.hovered {\n"
                                + "                width: 250px;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .sidebar ul {\n"
                                + "                list-style-type: none;\n"
                                + "                padding: 0;\n"
                                + "                margin: 0;\n"
                                + "            }\n"
                                + "            .sidebar ul li {\n"
                                + "                display: block;\n"
                                + "            }\n"
                                + "            .sidebar ul li a {\n"
                                + "                display: block;\n"
                                + "                position: relative;\n"
                                + "                white-space: nowrap;\n"
                                + "                overflow: hidden;\n"
                                + "                border-bottom: 1px solid #ddd;\n"
                                + "                color: #444;\n"
                                + "                text-align: left;\n"
                                + "            }\n"
                                + "             .table-wrapper {\n"
                                + "        background: #fff;\n"
                                + "        padding: 20px 25px;\n"
                                + "        margin: 30px auto;\n"
                                + "		border-radius: 3px;\n"
                                + "        box-shadow: 0 1px 1px rgba(0,0,0,.05);\n"
                                + "    }\n"
                                + "    .table-title {\n"
                                + "		color: #fff;\n"
                                + "		background: #40b2cd;		\n"
                                + "		padding: 16px 25px;\n"
                                + "		margin: -20px -25px 10px;\n"
                                + "		border-radius: 3px 3px 0 0;\n"
                                + "    }\n"
                                + "    .table-title h2 {\n"
                                + "        margin: 5px 0 0;\n"
                                + "        font-size: 24px;\n"
                                + "    }\n"
                                + "	.search-box {\n"
                                + "        position: relative;\n"
                                + "        float: right;\n"
                                + "    }\n"
                                + "	.search-box .input-group {\n"
                                + "		min-width: 300px;\n"
                                + "		position: absolute;\n"
                                + "		right: 0;\n"
                                + "	}\n"
                                + "	.search-box .input-group-addon, .search-box input {\n"
                                + "		border-color: #ddd;\n"
                                + "		border-radius: 0;\n"
                                + "	}	\n"
                                + "    .search-box input {\n"
                                + "        height: 34px;\n"
                                + "        padding-right: 35px;\n"
                                + "        background: #f4fcfd;\n"
                                + "        border: none;\n"
                                + "        border-radius: 2px !important;\n"
                                + "    }\n"
                                + "	.search-box input:focus {\n"
                                + "        background: #fff;\n"
                                + "	}\n"
                                + "	.search-box input::placeholder {\n"
                                + "        font-style: italic;\n"
                                + "    }\n"
                                + "	.search-box .input-group-addon {\n"
                                + "        min-width: 35px;\n"
                                + "        border: none;\n"
                                + "        background: transparent;\n"
                                + "        position: absolute;\n"
                                + "        right: 0;\n"
                                + "        z-index: 9;\n"
                                + "        padding: 6px 0;\n"
                                + "    }\n"
                                + "    .search-box i {\n"
                                + "        color: #a0a5b1;\n"
                                + "        font-size: 19px;\n"
                                + "        position: relative;\n"
                                + "        top: 2px;\n"
                                + "    }\n"
                                + "    table.table {\n"
                                + "        table-layout: fixed;\n"
                                + "        margin-top: 15px;\n"
                                + "    }\n"
                                + "    table.table tr th, table.table tr td {\n"
                                + "        border-color: #e9e9e9;\n"
                                + "    }\n"
                                + "    table.table th i {\n"
                                + "        font-size: 13px;\n"
                                + "        margin: 0 5px;\n"
                                + "        cursor: pointer;\n"
                                + "    }\n"
                                + "    table.table th:first-child {\n"
                                + "        width: 60px;\n"
                                + "    }\n"
                                + "    table.table th:last-child {\n"
                                + "        width: 120px;\n"
                                + "    }\n"
                                + "    table.table td a {\n"
                                + "        color: #a0a5b1;\n"
                                + "        display: inline-block;\n"
                                + "        margin: 0 5px;\n"
                                + "    }\n"
                                + "	table.table td a.view {\n"
                                + "        color: #03A9F4;\n"
                                + "    }\n"
                                + "    table.table td a.edit {\n"
                                + "        color: #FFC107;\n"
                                + "    }\n"
                                + "    table.table td a.delete {\n"
                                + "        color: #E34724;\n"
                                + "    }\n"
                                + "    table.table td i {\n"
                                + "        font-size: 19px;\n"
                                + "    }"
                                + "            .sidebar ul li a i {\n"
                                + "                display: inline-block;\n"
                                + "                width: 60px;\n"
                                + "                height: 60px;\n"
                                + "                line-height: 60px;\n"
                                + "                text-align: center;\n"
                                + "                -webkit-animation-duration: 0.7s;\n"
                                + "                -moz-animation-duration: 0.7s;\n"
                                + "                -o-animation-duration: 0.7s;\n"
                                + "                animation-duration: 0.7s;\n"
                                + "                -webkit-animation-fill-mode: both;\n"
                                + "                -moz-animation-fill-mode: both;\n"
                                + "                -o-animation-fill-mode: both;\n"
                                + "                animation-fill-mode: both;\n"
                                + "            }\n"
                                + "            .sidebar ul li a span {\n"
                                + "                display: inline-block;\n"
                                + "                height: 60px;\n"
                                + "                line-height: 60px;\n"
                                + "            }\n"
                                + "            .sidebar ul li a:hover {\n"
                                + "                background-color: #eee;\n"
                                + "            }\n"
                                + "            .sidebar ul li a:hover i {\n"
                                + "                -webkit-animation-name: swing;\n"
                                + "                -moz-animation-name: swing;\n"
                                + "                -o-animation-name: swing;\n"
                                + "                animation-name: swing;\n"
                                + "            }\n"
                                + "            .main {\n"
                                + "                position: relative;\n"
                                + "                display: block;\n"
                                + "                top: 50px;\n"
                                + "                left: 0;\n"
                                + "                padding: 15px;\n"
                                + "                padding-left: 75px;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .main.active {\n"
                                + "                padding-left: 275px;\n"
                                + "                -webkit-transition: all 0.2s ease-in-out;\n"
                                + "                transition: all 0.2s ease-in-out;\n"
                                + "            }\n"
                                + "            .main .jumbotron {\n"
                                + "                background-color: #fff;\n"
                                + "                padding: 30px !important;\n"
                                + "                border: 1px solid #dfe8f1;\n"
                                + "                -webkit-border-radius: 3px;\n"
                                + "                -moz-border-radius: 3px;\n"
                                + "                border-radius: 3px;\n"
                                + "            }\n"
                                + "            .main .jumbotron h1 {\n"
                                + "                font-size: 24px;\n"
                                + "                margin: 0;\n"
                                + "                padding: 0;\n"
                                + "                margin-bottom: 12px;\n"
                                + "            }\n"
                                + "            @-webkit-keyframes swing {\n"
                                + "                20% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, 15deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, 15deg);\n"
                                + "                }\n"
                                + "                40% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, -10deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, -10deg);\n"
                                + "                }\n"
                                + "                60% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, 5deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, 5deg);\n"
                                + "                }\n"
                                + "                80% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, -5deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, -5deg);\n"
                                + "                }\n"
                                + "                100% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, 0deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, 0deg);\n"
                                + "                }\n"
                                + "            }\n"
                                + "            @keyframes swing {\n"
                                + "                20% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, 15deg);\n"
                                + "                    -ms-transform: rotate3d(0, 0, 1, 15deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, 15deg);\n"
                                + "                }\n"
                                + "                40% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, -10deg);\n"
                                + "                    -ms-transform: rotate3d(0, 0, 1, -10deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, -10deg);\n"
                                + "                }\n"
                                + "                60% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, 5deg);\n"
                                + "                    -ms-transform: rotate3d(0, 0, 1, 5deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, 5deg);\n"
                                + "                }\n"
                                + "                80% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, -5deg);\n"
                                + "                    -ms-transform: rotate3d(0, 0, 1, -5deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, -5deg);\n"
                                + "                }\n"
                                + "                100% {\n"
                                + "                    -webkit-transform: rotate3d(0, 0, 1, 0deg);\n"
                                + "                    -ms-transform: rotate3d(0, 0, 1, 0deg);\n"
                                + "                    transform: rotate3d(0, 0, 1, 0deg);\n"
                                + "                }\n"
                                + "            }\n"
                                + "            .swing {\n"
                                + "                -webkit-transform-origin: top center;\n"
                                + "                -ms-transform-origin: top center;\n"
                                + "                transform-origin: top center;\n"
                                + "                -webkit-animation-name: swing;\n"
                                + "                animation-name: swing;\n"
                                + "            }\n"
                                + "        </style>\n"
                                + "    </head>\n"
                                + "    <body>\n"
                                + "        <!-- partial:index.partial.html -->\n"
                                + "        <div class=\"header\">\n"
                                + "            <a href=\"#\" id=\"menu-action\">\n"
                                + "                <i class=\"fa fa-bars\"></i>\n"
                                + "                <span>Close</span>\n"
                                + "            </a>\n"
                                + "            <div class=\"logo\">\n"
                                + "                <img src=\"images/logo.png\" alt=\"\" width=\"35\" height=\"35\"/>KERA LOKAL\n"
                                + "            </div>\n"
                                + "        </div>\n"
                                + "        <div class=\"sidebar\">\n"
                                + "            <ul>\n"
                                + "                <li><a href=\"./_home_seller\"><i class=\"fa fa-home\"></i><span>Home</span></a></li>\n"
                                + "                <li><a href=\"./seller_urusanPembayaran\"><i class=\"fa fa-credit-card\"></i><span>Manajemen Pembayaran</span></a></li>\n"
                                + "                <li><a href=\"./seller_urusanProduk\"><i class=\"fa fa-sitemap\"></i><span>Manajemen Barang</span></a></li>\n"
                                + "                <li><a href=\"./seller_urusanPengiriman\"><i class=\"fa fa-truck\"></i><span>Manajemen Pengiriman</span></a></li>\n"
                                + "                <li><a href=\"./seller_kotakMasuk\"><i class=\"fa fa-envelope\"></i><span>Inbox</span></a></li>\n"
                                + "                <li><a href=\"./seller_accountSetting?idToko_=" + idAkun + "\"><i class=\"fa fa-wrench\"></i><span>Pengaturan Akun</span></a></li>\n"
                                + "        <li><a href=\"./logout2_\"><i class=\"fa fa-power-off\"></i><span>Logout</span></a></li>\n"
                                + "            </ul> \n"
                                + "        </div>\n"
                                + "\n"
                                + "        <!-- Content -->\n"
                                + "        <div class=\"main\">\n"
                                + "            <div class=\"hipsum\">\n"
                                + "                <div class=\"panel panel-default\">\n"
                                + "                <div class=\"panel-heading\">\n"
                                + "                    Payment\n"
                                + "                </div>\n"
                                + "                <div class=\"panel-body\">\n"
                                + "                    <ul class=\"nav nav-tabs\">\n"
                                + "                        <li ><a href=\"./seller_kotakMasuk\" >Request Produk Masuk</a></li>\n"
                                + "                        <li ><a href=\"./seller_kotakMasuk_diterima\" >Diterima</a>\n"
                                + "                        <li class=\"active\"><a href=\"./seller_kotakMasuk_ditolak\" >Ditolak</a>\n"
                                + "                        </li>\n"
                                + "                    </ul>\n"
                                + "\n"
                                + "                    <div class=\"tab-content\">\n"
                                + "                        <div class=\"tab-pane fade active in\" id=\"home\">\n"
                                + "                            <div class=\"table-wrapper\">			\n"
                                + "            <div class=\"table-title\">\n"
                                + "                <div class=\"row\">\n"
                                + "					<div class=\"col-sm-6\">\n"
                                + "						<h2>Request <b>Masuk</b></h2>\n"
                                + "					</div>\n"
                                + "                </div>\n"
                                + "            </div>\n"
                                + "            <table class=\"table table-striped\">\n"
                                + "                <thead>\n"
                                + "                    <tr>\n"
                                + "                        <th>#</th>\n"
                                + "                        <th style=\"width: 22%;\">Nama Barang Request</th>\n"
                                + "                        <th style=\"width: 22%;\">Foto Barang</th>"
                                + "                        <th style=\"width: 22%;\">Opsi</th>"
                                + "                    </tr>\n"
                                + "                </thead>\n"
                                + "                <tbody>\n");
                        int urutan = 0;
                        for (int i = 0; i < products.size(); i++) {
                            urutan = urutan + 1;
                            out.println("                    <tr>\n"
                                    + "                        <td>" + urutan + "</td>\n"
                                    + "                        <td>" + products.get(i).getNama_produk() + "</td>\n"
                                    + "                        <td><img src=\"./productReqImage_loader?idProdukReq_=" + products.get(i).getId_produk() + "\" width=\"90\" height=\"50\"/></td>\n"
                                    + "                        <td>\n"
                                    + "                            <a href=\"./seller_requestProduk_details?idProdukReq_=" + products.get(i).getId_produk() + "\" class=\"edit\" title=\"Tolak\" data-toggle=\"tooltip\"><i class=\"material-icons\">remove_red_eye</i></a>\n"
                                    + "                            <a href=\"#\" class=\"delete\" title=\"Hapus\" data-toggle=\"tooltip\"><i class=\"material-icons\">delete</i></a>\n"
                                    + "                        </td>\n"
                                    + "                    </tr>\n");
                        }
                        out.println("</table>\n"
                                + "        </div>"
                                + "                         </div>\n"
                                + "                    </div>\n"
                                + "                </div>\n"
                                + "            </div>"
                                + "\n"
                                + "\n"
                                + "            </div>\n"
                                + "            "
                                + "        </div>\n"
                                + "        <!-- partial -->\n"
                                + "        <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\n"
                                + "        <script>\n"
                                + "            $('#menu-action').click(function () {\n"
                                + "                $('.sidebar').toggleClass('active');\n"
                                + "                $('.main').toggleClass('active');\n"
                                + "                $(this).toggleClass('active');\n"
                                + "\n"
                                + "                if ($('.sidebar').hasClass('active')) {\n"
                                + "                    $(this).find('i').addClass('fa-close');\n"
                                + "                    $(this).find('i').removeClass('fa-bars');\n"
                                + "                } else {\n"
                                + "                    $(this).find('i').addClass('fa-bars');\n"
                                + "                    $(this).find('i').removeClass('fa-close');\n"
                                + "                }\n"
                                + "            });\n"
                                + "\n"
                                + "            // Add hover feedback on menu\n"
                                + "            $('#menu-action').hover(function () {\n"
                                + "                $('.sidebar').toggleClass('hovered');\n"
                                + "            });\n"
                                + "        </script>\n"
                                + "\n"
                                + "    </body>\n"
                                + "</html>");
                    } finally {
                        out.close();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(seller_kotakMasuk.class.getName()).log(Level.SEVERE, null, ex);
                    String pesan_error = ex.getMessage();
                    out.println("<!DOCTYPE html>\n"
                            + "<html lang=\"en\" >\n"
                            + "<head>\n"
                            + "  <meta charset=\"UTF-8\">\n"
                            + "  <title>Error 500 alert - #CodePenChallenges</title>\n"
                            + "  <link href=\"https://fonts.googleapis.com/css?family=Inconsolata:400,700\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css\">\n"
                            + "<style type=\"text/css\">\n"
                            + "html,\n"
                            + "body {\n"
                            + "  height: 100%;\n"
                            + "}\n"
                            + "body {\n"
                            + "  display: grid;\n"
                            + "  width: 100%;\n"
                            + "  font-family: Inconsolata, monospace;\n"
                            + "}\n"
                            + "body div#error {\n"
                            + "  position: relative;\n"
                            + "  margin: auto;\n"
                            + "  padding: 20px;\n"
                            + "  z-index: 2;\n"
                            + "}\n"
                            + "body div#error div#box {\n"
                            + "  position: absolute;\n"
                            + "  top: 0;\n"
                            + "  left: 0;\n"
                            + "  width: 100%;\n"
                            + "  height: 100%;\n"
                            + "  border: 1px solid #000;\n"
                            + "}\n"
                            + "body div#error div#box:before,\n"
                            + "body div#error div#box:after {\n"
                            + "  content: '';\n"
                            + "  position: absolute;\n"
                            + "  top: 0;\n"
                            + "  left: 0;\n"
                            + "  width: 100%;\n"
                            + "  height: 100%;\n"
                            + "  box-shadow: inset 0px 0px 0px 1px #000;\n"
                            + "  mix-blend-mode: multiply;\n"
                            + "  animation: dance 2s infinite steps(1);\n"
                            + "}\n"
                            + "body div#error div#box:before {\n"
                            + "  clip-path: polygon(0 0, 65% 0, 35% 100%, 0 100%);\n"
                            + "  box-shadow: inset 0px 0px 0px 1px currentColor;\n"
                            + "  color: #f0f;\n"
                            + "}\n"
                            + "body div#error div#box:after {\n"
                            + "  clip-path: polygon(65% 0, 100% 0, 100% 100%, 35% 100%);\n"
                            + "  animation-duration: 0.5s;\n"
                            + "  animation-direction: alternate;\n"
                            + "  box-shadow: inset 0px 0px 0px 1px currentColor;\n"
                            + "  color: #0ff;\n"
                            + "}\n"
                            + "body div#error h3 {\n"
                            + "  position: relative;\n"
                            + "  font-size: 5vw;\n"
                            + "  font-weight: 700;\n"
                            + "  text-transform: uppercase;\n"
                            + "  animation: blink 1.3s infinite steps(1);\n"
                            + "}\n"
                            + "body div#error h3:before,\n"
                            + "body div#error h3:after {\n"
                            + "  content: 'ERROR 500';\n"
                            + "  position: absolute;\n"
                            + "  top: -1px;\n"
                            + "  left: 0;\n"
                            + "  mix-blend-mode: soft-light;\n"
                            + "  animation: dance 2s infinite steps(2);\n"
                            + "}\n"
                            + "body div#error h3:before {\n"
                            + "  clip-path: polygon(0 0, 100% 0, 100% 50%, 0 50%);\n"
                            + "  color: #f0f;\n"
                            + "  animation: shiftright 2s steps(2) infinite;\n"
                            + "}\n"
                            + "body div#error h3:after {\n"
                            + "  clip-path: polygon(0 100%, 100% 100%, 100% 50%, 0 50%);\n"
                            + "  color: #0ff;\n"
                            + "  animation: shiftleft 2s steps(2) infinite;\n"
                            + "}\n"
                            + "body div#error p {\n"
                            + "  position: relative;\n"
                            + "  margin-bottom: 8px;\n"
                            + "}\n"
                            + "body div#error p span {\n"
                            + "  position: relative;\n"
                            + "  display: inline-block;\n"
                            + "  font-weight: bold;\n"
                            + "  color: #000;\n"
                            + "  animation: blink 3s steps(1) infinite;\n"
                            + "}\n"
                            + "body div#error p span:before,\n"
                            + "body div#error p span:after {\n"
                            + "  content: '}{|@#%_!';\n"
                            + "  position: absolute;\n"
                            + "  top: -1px;\n"
                            + "  left: 0;\n"
                            + "  mix-blend-mode: multiply;\n"
                            + "}\n"
                            + "body div#error p span:before {\n"
                            + "  clip-path: polygon(0 0, 100% 0, 100% 50%, 0 50%);\n"
                            + "  color: #f0f;\n"
                            + "  animation: shiftright 1.5s steps(2) infinite;\n"
                            + "}\n"
                            + "body div#error p span:after {\n"
                            + "  clip-path: polygon(0 100%, 100% 100%, 100% 50%, 0 50%);\n"
                            + "  color: #0ff;\n"
                            + "  animation: shiftleft 1.7s steps(2) infinite;\n"
                            + "}\n"
                            + "@-moz-keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-moz-keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-moz-keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-moz-keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "</style>\n"
                            + "\n"
                            + "</head>\n"
                            + "<body>\n"
                            + "<!-- partial:index.partial.html -->\n"
                            + "<div id=\"error\">\n"
                            + "  <div id=\"box\"></div>\n"
                            + "  <h3>ERROR 500</h3>\n"
                            + "  <p>Inter<span>nal Serv</span>er <span>Err0r*=@#!</span>234Z_</p>\n"
                            + "  <p>" + pesan_error + "</p>\n"
                            + "</div>\n"
                            + "<!-- partial -->\n"
                            + "  \n"
                            + "</body>\n"
                            + "</html>");
                }
            } else {
                PrintWriter output = response.getWriter();
                output.println("<script type=\"text/javascript\">");
                output.println("alert('BUKAN HAK KAU!');");
                output.println("location='./halaman_login/index.html';");
                output.println("</script>");
                output.close();
            }

        } else {
            response.sendRedirect("./index.html");
        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
