/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homenya_admin;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import kelas_java.db_connection;

/**
 *
 * @author ASUS
 */
@WebServlet(name = "_home_admin", urlPatterns = {"/_home_admin"})
public class _home_admin extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        PrintWriter out = response.getWriter();
        String nama_user = null;
        String idAkun = null;
        String levelAkun = null;

        Cookie[] cookies = request.getCookies();
        if (cookies != null) {
            for (Cookie cookie : cookies) {
                if (cookie.getName().equals("namaUser")) {
                    nama_user = cookie.getValue();
                }
                if (cookie.getName().equals("idAkun")) {
                    idAkun = cookie.getValue();
                }
                if (cookie.getName().equals("levelAkun")) {
                    levelAkun = cookie.getValue();
                }
            }
            if (levelAkun.equals("admin")) {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn = db_connection.connect_to_Db();

                    PreparedStatement psjmlhmetodebayar = conn.prepareStatement("SELECT COUNT(*) AS jumlahmetodebayar FROM tabel_metodebayar");
                    ResultSet rs1 = psjmlhmetodebayar.executeQuery();
                    int jumlah_metodebayar=0;
                    
                    while(rs1.next()){
                        jumlah_metodebayar = rs1.getInt("jumlahmetodebayar");
                    }
                    
                    PreparedStatement psjmlhtoko = conn.prepareStatement("SELECT COUNT(*) AS jumlahtoko FROM tabel_toko");
                    ResultSet rs2 = psjmlhtoko.executeQuery();
                    int jumlah_toko=0;
                    
                    while(rs2.next()){
                        jumlah_toko = rs2.getInt("jumlahtoko");
                    }
                    
                    PreparedStatement psjmlhcustomer = conn.prepareStatement("SELECT COUNT(*) AS jumlahcustomer FROM tabel_customer");
                    ResultSet rs3 = psjmlhcustomer.executeQuery();
                    int jumlah_user=0;
                    
                    while(rs3.next()){
                        jumlah_user = rs3.getInt("jumlahcustomer");
                    }
                    
                    PreparedStatement psjmlhmetodekirim = conn.prepareStatement("SELECT COUNT(*) AS jumlahmetodekirim FROM tabel_kurir");
                    ResultSet rs4 = psjmlhmetodekirim.executeQuery();
                    int jumlah_metodekirim=0;
                    
                    while(rs4.next()){
                        jumlah_metodekirim = rs4.getInt("jumlahmetodekirim");
                    }

                    try {
                        out.println("<!DOCTYPE html>\n"
                                + "<html lang=\"en\" >\n"
                                + "<head>\n"
                                + "  <meta charset=\"UTF-8\">\n"
                                + "  <title>Admin Panel</title>\n"
                                + "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\n"
                                + "<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>\n"
                                + "<style type=\"text/css\">\n"
                                + "@import \"https://designmodo.github.io/Flat-UI/dist/css/flat-ui.min.css\";\n"
                                + "@import \"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\";\n"
                                + "@import \"https://daneden.github.io/animate.css/animate.min.css\";\n"
                                + "/*-------------------------------*/\n"
                                + "/*           VARIABLES           */\n"
                                + "/*-------------------------------*/\n"
                                + "body {\n"
                                + "  position: relative;\n"
                                + "  overflow-x: hidden;\n"
                                + "}\n"
                                + "body,\n"
                                + "html {\n"
                                + "  height: 100%;\n"
                                + "  background-color: white;\n"
                                + "}\n"
                                + ".nav .open > a {\n"
                                + "  background-color: transparent;\n"
                                + "}\n"
                                + ".nav .open > a:hover {\n"
                                + "  background-color: transparent;\n"
                                + "}\n"
                                + ".nav .open > a:focus {\n"
                                + "  background-color: transparent;\n"
                                + "}\n"
                                + "/*-------------------------------*/\n"
                                + "/*           Wrappers            */\n"
                                + "/*-------------------------------*/\n"
                                + "#wrapper {\n"
                                + "  -moz-transition: all 0.5s ease;\n"
                                + "  -o-transition: all 0.5s ease;\n"
                                + "  -webkit-transition: all 0.5s ease;\n"
                                + "  padding-left: 0;\n"
                                + "  transition: all 0.5s ease;\n"
                                + "}\n"
                                + "#wrapper.toggled {\n"
                                + "  padding-left: 220px;\n"
                                + "}\n"
                                + "#wrapper.toggled #sidebar-wrapper {\n"
                                + "  width: 220px;\n"
                                + "}\n"
                                + "#wrapper.toggled #page-content-wrapper {\n"
                                + "  margin-right: -220px;\n"
                                + "  position: absolute;\n"
                                + "}\n"
                                + "#sidebar-wrapper {\n"
                                + "  -moz-transition: all 0.5s ease;\n"
                                + "  -o-transition: all 0.5s ease;\n"
                                + "  -webkit-transition: all 0.5s ease;\n"
                                + "  background: #1a1a1a;\n"
                                + "  height: 100%;\n"
                                + "  left: 220px;\n"
                                + "  margin-left: -220px;\n"
                                + "  overflow-x: hidden;\n"
                                + "  overflow-y: auto;\n"
                                + "  transition: all 0.5s ease;\n"
                                + "  width: 0;\n"
                                + "  z-index: 1000;\n"
                                + "}\n"
                                + "#sidebar-wrapper::-webkit-scrollbar {\n"
                                + "  display: none;\n"
                                + "}\n"
                                + "#page-content-wrapper {\n"
                                + "  padding-top: 70px;\n"
                                + "  width: 100%;\n"
                                + "}\n"
                                + "/*-------------------------------*/\n"
                                + "/*     Sidebar nav styles        */\n"
                                + "/*-------------------------------*/\n"
                                + ".sidebar-nav {\n"
                                + "  list-style: none;\n"
                                + "  margin: 0;\n"
                                + "  padding: 0;\n"
                                + "  position: absolute;\n"
                                + "  top: 0;\n"
                                + "  width: 220px;\n"
                                + "}\n"
                                + ".sidebar-nav li {\n"
                                + "  display: inline-block;\n"
                                + "  line-height: 20px;\n"
                                + "  position: relative;\n"
                                + "  width: 100%;\n"
                                + "}\n"
                                + ".sidebar-nav li:before {\n"
                                + "  background-color: #F2849E;\n"
                                + "  content: '';\n"
                                + "  height: 100%;\n"
                                + "  left: 0;\n"
                                + "  position: absolute;\n"
                                + "  top: 0;\n"
                                + "  transition: width 0.2s ease-in;\n"
                                + "  width: 3px;\n"
                                + "  z-index: -1;\n"
                                + "}\n"
                                + ".sidebar-nav li:first-child a {\n"
                                + "  background-color: #F2849E;\n"
                                + "  color: #ffffff;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(2):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(3):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(4):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(5):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(6):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(7):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(8):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:nth-child(9):before {\n"
                                + "  background-color: #F2849E;\n"
                                + "}\n"
                                + ".sidebar-nav li:hover:before {\n"
                                + "  transition: width 0.2s ease-in;\n"
                                + "  width: 100%;\n"
                                + "}\n"
                                + ".sidebar-nav li a {\n"
                                + "  color: #dddddd;\n"
                                + "  display: block;\n"
                                + "  padding: 10px 15px 10px 30px;\n"
                                + "  text-decoration: none;\n"
                                + "}\n"
                                + ".sidebar-nav li.open:hover before {\n"
                                + "  transition: width 0.2s ease-in;\n"
                                + "  width: 100%;\n"
                                + "}\n"
                                + ".sidebar-nav .dropdown-menu {\n"
                                + "  background-color: #683E48;\n"
                                + "  border-radius: 0;\n"
                                + "  border: none;\n"
                                + "  box-shadow: none;\n"
                                + "  margin: 0;\n"
                                + "  padding: 0;\n"
                                + "  position: relative;\n"
                                + "  width: 100%;\n"
                                + "}\n"
                                + ".sidebar-nav li a:hover,\n"
                                + ".sidebar-nav li a:active,\n"
                                + ".sidebar-nav li a:focus,\n"
                                + ".sidebar-nav li.open a:hover,\n"
                                + ".sidebar-nav li.open a:active,\n"
                                + ".sidebar-nav li.open a:focus {\n"
                                + "  background-color: transparent;\n"
                                + "  color: #ffffff;\n"
                                + "  text-decoration: none;\n"
                                + "}\n"
                                + ".sidebar-nav > .sidebar-brand {\n"
                                + "  font-size: 20px;\n"
                                + "  height: 65px;\n"
                                + "  line-height: 44px;\n"
                                + "}\n"
                                + "/*-------------------------------*/\n"
                                + "/*       Hamburger-Cross         */\n"
                                + "/*-------------------------------*/\n"
                                + ".hamburger {\n"
                                + "  background: transparent;\n"
                                + "  border: none;\n"
                                + "  display: block;\n"
                                + "  height: 32px;\n"
                                + "  margin-left: 15px;\n"
                                + "  position: fixed;\n"
                                + "  top: 20px;\n"
                                + "  width: 32px;\n"
                                + "  z-index: 999;\n"
                                + "}\n"
                                + ".hamburger:hover {\n"
                                + "  outline: none;\n"
                                + "}\n"
                                + ".hamburger:focus {\n"
                                + "  outline: none;\n"
                                + "}\n"
                                + ".hamburger:active {\n"
                                + "  outline: none;\n"
                                + "}\n"
                                + ".hamburger.is-closed:before {\n"
                                + "  -webkit-transform: translate3d(0, 0, 0);\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  color: #ffffff;\n"
                                + "  content: '';\n"
                                + "  display: block;\n"
                                + "  font-size: 14px;\n"
                                + "  line-height: 32px;\n"
                                + "  opacity: 0;\n"
                                + "  text-align: center;\n"
                                + "  width: 100px;\n"
                                + "}\n"
                                + ".hamburger.is-closed:hover before {\n"
                                + "  -webkit-transform: translate3d(-100px, 0, 0);\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  display: block;\n"
                                + "  opacity: 1;\n"
                                + "}\n"
                                + ".hamburger.is-closed:hover .hamb-top {\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  top: 0;\n"
                                + "}\n"
                                + ".hamburger.is-closed:hover .hamb-bottom {\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  bottom: 0;\n"
                                + "}\n"
                                + ".hamburger.is-closed .hamb-top {\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  background-color: rgba(255, 255, 255, 0.7);\n"
                                + "  top: 5px;\n"
                                + "}\n"
                                + ".hamburger.is-closed .hamb-middle {\n"
                                + "  background-color: rgba(255, 255, 255, 0.7);\n"
                                + "  margin-top: -2px;\n"
                                + "  top: 50%;\n"
                                + "}\n"
                                + ".hamburger.is-closed .hamb-bottom {\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  background-color: rgba(255, 255, 255, 0.7);\n"
                                + "  bottom: 5px;\n"
                                + "}\n"
                                + ".hamburger.is-closed .hamb-top,\n"
                                + ".hamburger.is-closed .hamb-middle,\n"
                                + ".hamburger.is-closed .hamb-bottom,\n"
                                + ".hamburger.is-open .hamb-top,\n"
                                + ".hamburger.is-open .hamb-middle,\n"
                                + ".hamburger.is-open .hamb-bottom {\n"
                                + "  height: 4px;\n"
                                + "  left: 0;\n"
                                + "  position: absolute;\n"
                                + "  width: 100%;\n"
                                + "}\n"
                                + ".hamburger.is-open .hamb-top {\n"
                                + "  -webkit-transform: rotate(45deg);\n"
                                + "  -webkit-transition: -webkit-transform 0.2s cubic-bezier(0.73, 1, 0.28, 0.08);\n"
                                + "  background-color: #fff;\n"
                                + "  margin-top: -2px;\n"
                                + "  top: 50%;\n"
                                + "}\n"
                                + ".hamburger.is-open .hamb-middle {\n"
                                + "  background-color: #fff;\n"
                                + "  display: none;\n"
                                + "}\n"
                                + ".hamburger.is-open .hamb-bottom {\n"
                                + "  -webkit-transform: rotate(-45deg);\n"
                                + "  -webkit-transition: -webkit-transform 0.2s cubic-bezier(0.73, 1, 0.28, 0.08);\n"
                                + "  background-color: #fff;\n"
                                + "  margin-top: -2px;\n"
                                + "  top: 50%;\n"
                                + "}\n"
                                + ".hamburger.is-open:before {\n"
                                + "  -webkit-transform: translate3d(0, 0, 0);\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  color: #ffffff;\n"
                                + "  content: '';\n"
                                + "  display: block;\n"
                                + "  font-size: 14px;\n"
                                + "  line-height: 32px;\n"
                                + "  opacity: 0;\n"
                                + "  text-align: center;\n"
                                + "  width: 100px;\n"
                                + "}\n"
                                + ".hamburger.is-open:hover before {\n"
                                + "  -webkit-transform: translate3d(-100px, 0, 0);\n"
                                + "  -webkit-transition: all 0.35s ease-in-out;\n"
                                + "  display: block;\n"
                                + "  opacity: 1;\n"
                                + "}"
                                + ".panel {\n"
                                + "  border: 0; }\n"
                                + "\n"
                                + ".panel-container {\n"
                                + "  padding-top: 20px; }\n"
                                + "\n"
                                + ".panel-heading .fa-toggle-up, .panel-heading .fa-toggle-down {\n"
                                + "  font-size: 17px; }\n"
                                + "\n"
                                + ".panel-primary > .panel-heading {\n"
                                + "  background-color: #30a5ff;\n"
                                + "  color: #fff;\n"
                                + "  border: none; }\n"
                                + "\n"
                                + ".panel-success > .panel-heading {\n"
                                + "  background-color: #8ad919;\n"
                                + "  color: #fff;\n"
                                + "  border: none; }\n"
                                + "\n"
                                + ".panel-info > .panel-heading {\n"
                                + "  background-color: #30a5ff;\n"
                                + "  color: #fff;\n"
                                + "  border: none; }\n"
                                + "\n"
                                + ".panel-warning > .panel-heading {\n"
                                + "  background-color: #ffb53e;\n"
                                + "  color: #fff;\n"
                                + "  border: none; }\n"
                                + "\n"
                                + ".panel-danger > .panel-heading {\n"
                                + "  background-color: #f9243f;\n"
                                + "  color: #fff;\n"
                                + "  border: none; }\n"
                                + "\n"
                                + ".panel-primary .panel-settings, .panel-primary .panel-toggle, .panel-success .panel-settings, .panel-success .panel-toggle, .panel-info .panel-settings, .panel-info .panel-toggle, .panel-warning .panel-settings, .panel-warning .panel-toggle, .panel-danger .panel-settings, .panel-danger .panel-toggle {\n"
                                + "  border: none;\n"
                                + "  color: #fff;\n"
                                + "  background-color: rgba(255, 255, 255, 0.2); }\n"
                                + "\n"
                                + ".panel-primary .panel-settings:hover, .panel-primary .panel-toggle:hover, .panel-success .panel-settings:hover, .panel-success .panel-toggle:hover, .panel-info .panel-settings:hover, .panel-info .panel-toggle:hover, .panel-warning .panel-settings:hover, .panel-warning .panel-toggle:hover, .panel-danger .panel-settings:hover, .panel-danger .panel-toggle:hover {\n"
                                + "  border: none;\n"
                                + "  color: #fff;\n"
                                + "  background-color: rgba(255, 255, 255, 0.4); }\n"
                                + "\n"
                                + ".panel-blue {\n"
                                + "  background: #30a5ff;\n"
                                + "  color: #fff; }\n"
                                + "\n"
                                + ".panel-teal {\n"
                                + "  background: #1ebfae;\n"
                                + "  color: #fff; }\n"
                                + "\n"
                                + ".panel-orange {\n"
                                + "  background: #ffb53e;\n"
                                + "  color: #fff; }\n"
                                + "\n"
                                + ".panel-red {\n"
                                + "  background: #f9243f;\n"
                                + "  color: #fff; }\n"
                                + "\n"
                                + ".dark-overlay {\n"
                                + "  background: rgba(0, 0, 0, 0.05); }\n"
                                + "\n"
                                + ".panel-blue p, .panel-teal p, .panel-orange p, .panel-red p {\n"
                                + "  color: rgba(255, 255, 255, 0.75); }\n"
                                + "\n"
                                + ".panel-heading {\n"
                                + "  font-size: 20px;\n"
                                + "  font-weight: 300;\n"
                                + "  letter-spacing: 0.025em;\n"
                                + "  height: 60px;\n"
                                + "  line-height: 38px; }\n"
                                + "\n"
                                + ".panel-default .panel-heading {\n"
                                + "  background: #fff;\n"
                                + "  border-bottom: 1px solid #e9ecf2;\n"
                                + "  color: #444444; }\n"
                                + "\n"
                                + ".panel-footer {\n"
                                + "  background: #fff;\n"
                                + "  border-top: 1px solid #e9ecf2; }\n"
                                + "\n"
                                + ".panel-widget {\n"
                                + "  padding: 10px 0;\n"
                                + "  position: relative;\n"
                                + "  box-shadow: none;\n"
                                + "  border-radius: 0;\n"
                                + "  background: none;\n"
                                + "  text-align: center;\n"
                                + "  color: #333; }\n"
                                + "\n"
                                + ".panel-widget .panel-footer {\n"
                                + "  border: 0;\n"
                                + "  text-align: center; }\n"
                                + "\n"
                                + ".panel-footer .input-group {\n"
                                + "  padding: 0px;\n"
                                + "  margin: 0 -5px; }\n"
                                + "\n"
                                + ".panel-footer .input-group-btn:last-child > .btn, .panel-footer .input-group-btn:last-child > .btn-group {\n"
                                + "  margin: 0; }\n"
                                + "\n"
                                + ".panel-widget .panel-footer a {\n"
                                + "  color: #999; }\n"
                                + "\n"
                                + ".panel-widget .panel-footer a:hover {\n"
                                + "  color: #666;\n"
                                + "  text-decoration: none; }\n"
                                + "\n"
                                + ".panel-widget .text-muted {\n"
                                + "  margin-top: -6px;\n"
                                + "  text-transform: uppercase;\n"
                                + "  font-weight: bold;\n"
                                + "  font-size: 0.8em; }\n"
                                + "\n"
                                + ".panel-widget .large {\n"
                                + "  color: #373b45;\n"
                                + "  font-size: 3em; }\n"
                                + "\n"
                                + ".panel-settings {\n"
                                + "  list-style: none;\n"
                                + "  padding: 0;\n"
                                + "  margin: 0; }\n"
                                + "\n"
                                + ".panel-settings .dropdown a.dropdown-toggle, .panel-settings a {\n"
                                + "  padding: 0;\n"
                                + "  background: none;\n"
                                + "  color: #7c7c7c; }\n"
                                + "\n"
                                + ".panel-settings a, .panel-toggle {\n"
                                + "  width: 40px;\n"
                                + "  padding: 2px 0 0 0; }\n"
                                + "\n"
                                + ".panel-settings:hover, .panel-toggle:hover, .panel-settings .dropdown a.dropdown-toggle:hover, .panel-settings:active, .panel-toggle:active, .panel-settings .dropdown a.dropdown-toggle:active, .panel-settings:focus, .panel-toggle:focus, .panel-settings .dropdown a.dropdown-toggle:focus {\n"
                                + "  background: #f1f4f7;\n"
                                + "  color: #444444; }\n"
                                + "\n"
                                + ".panel-settings, .panel-toggle {\n"
                                + "  display: inline-block;\n"
                                + "  margin: -1px -5px 0 15px !important;\n"
                                + "  border-radius: 4px;\n"
                                + "  text-align: center;\n"
                                + "  border: 1px solid #e9ecf2;\n"
                                + "  color: #7c7c7c;\n"
                                + "  background: #fff;\n"
                                + "  width: 42px; }\n"
                                + "\n"
                                + ".panel-settings {\n"
                                + "  width: 42px;\n"
                                + "  border-top-right-radius: 4px;\n"
                                + "  border-bottom-right-radius: 4px; }\n"
                                + "\n"
                                + ".panel-settings li.dropdown {\n"
                                + "  margin: 0;\n"
                                + "  padding: 0; }\n"
                                + "/*-------------------------------*/\n"
                                + "/*          Dark Overlay         */\n"
                                + "/*-------------------------------*/\n"
                                + ".overlay {\n"
                                + "  position: fixed;\n"
                                + "  display: none;\n"
                                + "  width: 100%;\n"
                                + "  height: 100%;\n"
                                + "  top: 0;\n"
                                + "  left: 0;\n"
                                + "  right: 0;\n"
                                + "  bottom: 0;\n"
                                + "  background-color: rgba(0, 0, 0, 0.4);\n"
                                + "  z-index: 1;\n"
                                + "}\n"
                                + "/* SOME DEMO STYLES - NOT REQUIRED */\n"
                                + "body,\n"
                                + "html {\n"
                                + "  background-color: #847676;\n"
                                + "}\n"
                                + "body h1,\n"
                                + "body h2,\n"
                                + "body h3,\n"
                                + "body h4 {\n"
                                + "  color: rgba(255, 255, 255, 0.9);\n"
                                + "}\n"
                                + "body p,\n"
                                + "body blockquote {\n"
                                + "  color: rgba(255, 255, 255, 0.7);\n"
                                + "}\n"
                                + "body a {\n"
                                + "  color: rgba(255, 255, 255, 0.8);\n"
                                + "  text-decoration: underline;\n"
                                + "}\n"
                                + "body a:hover {\n"
                                + "  color: #fff;\n"
                                + "}\n"
                                + "</style>\n"
                                + "\n"
                                + "</head>\n"
                                + "<body>\n"
                                + "<!-- partial:index.partial.html -->\n"
                                + "<div id=\"wrapper\">\n"
                                + "        <div class=\"overlay\"></div>\n"
                                + "    \n"
                                + "        <!-- Sidebar -->\n"
                                + "        <nav class=\"navbar navbar-inverse navbar-fixed-top\" id=\"sidebar-wrapper\" role=\"navigation\">\n"
                                + "            <ul class=\"nav sidebar-nav\">\n"
                                + "                <li class=\"sidebar-brand\">\n"
                                + "                    <a href=\"#\"><img src=\"images/logo.png\" alt=\"\" width=\"35\" height=\"35\"/>\n"
                                + "                       KERA LOKAL\n"
                                + "                    </a>\n"
                                + "                </li>\n"
                                + "                <li>\n"
                                + "                    <a href=\"#\"><i class=\"fa fa-fw fa-home\"></i> Home</a>\n"
                                + "                </li>\n"
                                + "                \n"
                                + "                <li class=\"dropdown\">\n"
                                + "                  <a href=\"#\" data-toggle=\"dropdown\"><i class=\"fa fa-fw fa-truck\"></i>Jasa Pengirim<span class=\"caret\"></span></a>\n"
                                + "                  <ul class=\"dropdown-menu\" role=\"menu\">\n"
                                + "                    <li class=\"dropdown-header\"> </li>\n"
                                + "                    <li><a href=\"./_urusanPengiriman\">Tambah Jasa Kirim</a></li>\n"
                                + "                    <li><a href=\"./view_urusanPengiriman\">Daftar Jasa Pengirim Tersedia</a></li>\n"
                                + "                  </ul>\n"
                                + "                </li>\n"
                                + "                \n"
                                + "                <li class=\"dropdown\">\n"
                                + "                  <a href=\"#\" data-toggle=\"dropdown\"><i class=\"fa fa-fw fa-street-view\"></i>Toko<span class=\"caret\"></span></a>\n"
                                + "                  <ul class=\"dropdown-menu\" role=\"menu\">\n"
                                + "                    <li class=\"dropdown-header\"> </li>\n"
                                + "                    <li><a href=\"./_urusanToko\">Tambah Toko</a></li>\n"
                                + "                    <li><a href=\"./view_urusanToko\">Daftar Toko yang Tersedia</a></li>\n"
                                + "                  </ul>\n"
                                + "                </li>\n"
                                + "                \n"
                                + "                <li class=\"dropdown\">\n"
                                + "                  <a href=\"#\" data-toggle=\"dropdown\"><i class=\"fa fa-fw fa-credit-card\"></i>Pembayaran<span class=\"caret\"></span></a>\n"
                                + "                  <ul class=\"dropdown-menu\" role=\"menu\">\n"
                                + "                    <li class=\"dropdown-header\"> </li>\n"
                                + "                    <li><a href=\"./_urusanPembayaran\">Tambah Metode Bayar</a></li>\n"
                                + "                    <li><a href=\"./view_urusanPembayaran\">Daftar Metode Tersedia</a></li>\n"
                                + "                  </ul>\n"
                                + "                </li>\n"
                                + "                \n"
                                + "                <li>\n"
                                + "                    <a href=\"./_x_pengaturanakunAdmin?idAdmin_="+idAkun+"\"><i class=\"fa fa-fw fa-cogs\"></i> Pengaturan Akun</a>\n"
                                + "                </li>\n"
                                + "                <li>\n"
                                + "                    <a href=\"./logout2_\"><i class=\"fa fa-fw fa-power-off\"></i> Logout</a>\n"
                                + "                </li>\n"
                                + "            </ul>\n"
                                + "        </nav>\n"
                                + "        <!-- /#sidebar-wrapper -->\n"
                                + "\n"
                                + "        <!-- Page Content -->\n"
                                + "        <marquee><h2>Selamat datang, " + nama_user + "</h2></marquee>\n"
                                + "        <div id=\"page-content-wrapper\">\n"
                                + "          <button type=\"button\" class=\"hamburger is-closed animated fadeInLeft\" data-toggle=\"offcanvas\">\n"
                                + "            <span class=\"hamb-top\"></span>\n"
                                + "            <span class=\"hamb-middle\"></span>\n"
                                + "            <span class=\"hamb-bottom\"></span>\n"
                                + "          </button>\n"
                                + "            \n"
                                + "            <div class=\"container\">\n"
                                + "                \n"
                                + "                <!--<p>isi konten bisa disini</p>-->\n"
                                + "                <div class=\"row\">\n"
                                + "                    <div class=\"panel panel-container\">\n"
                                + "			<div class=\"row\">\n"
                                + "				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\n"
                                + "					<div class=\"panel panel-teal panel-widget border-right\">\n"
                                + "						<div class=\"row no-padding\"><em class=\"fa fa-credit-card\"></em>\n"
                                + "							<div class=\"large\">"+jumlah_metodebayar+"</div>\n"
                                + "							<div class=\"text-muted\">Metode Bayar Tersedia</div>\n"
                                + "						</div>\n"
                                + "					</div>\n"
                                + "				</div>\n"
                                + "				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\n"
                                + "					<div class=\"panel panel-blue panel-widget border-right\">\n"
                                + "						<div class=\"row no-padding\"><em class=\"fa fa-th-large\"></em>\n"
                                + "							<div class=\"large\">"+jumlah_toko+"</div>\n"
                                + "							<div class=\"text-muted\">Toko Kerajinan Lokal</div>\n"
                                + "						</div>\n"
                                + "					</div>\n"
                                + "				</div>\n"
                                + "				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\n"
                                + "					<div class=\"panel panel-orange panel-widget border-right\">\n"
                                + "						<div class=\"row no-padding\"><em class=\"fa fa-xl fa-users\"></em>\n"
                                + "							<div class=\"large\">"+jumlah_user+"</div>\n"
                                + "							<div class=\"text-muted\">Customer Terdaftar</div>\n"
                                + "						</div>\n"
                                + "					</div>\n"
                                + "				</div>\n"
                                + "				<div class=\"col-xs-6 col-md-3 col-lg-3 no-padding\">\n"
                                + "					<div class=\"panel panel-red panel-widget \">\n"
                                + "						<div class=\"row no-padding\"><em class=\"fa fa-xl fa-truck\"></em>\n"
                                + "							<div class=\"large\">"+jumlah_metodekirim+"</div>\n"
                                + "							<div class=\"text-muted\">Metode Pengiriman Tersedia</div>\n"
                                + "						</div>\n"
                                + "					</div>\n"
                                + "				</div>\n"
                                + "			</div><!--/.row-->\n"
                                + "		</div>"
                                + "                    <div class=\"col-lg-8 col-lg-offset-2\">\n"
                                + "                        <p>isi konten bisa disini3</p>\n"
                                + "                    </div>\n"
                                + "                </div>\n"
                                + "            </div>\n"
                                + "        </div>\n"
                                + "        <!-- /#page-content-wrapper -->\n"
                                + "\n"
                                + "    </div>\n"
                                + "    <!-- /#wrapper -->\n"
                                + "<!-- partial -->\n"
                                + "  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\n"
                                + "<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'></script>\n"
                                + "<script>\n"
                                + "$(document).ready(function () {\n"
                                + "  var trigger = $('.hamburger'),\n"
                                + "      overlay = $('.overlay'),\n"
                                + "     isClosed = false;\n"
                                + "\n"
                                + "    trigger.click(function () {\n"
                                + "      hamburger_cross();      \n"
                                + "    });\n"
                                + "\n"
                                + "    function hamburger_cross() {\n"
                                + "\n"
                                + "      if (isClosed == true) {          \n"
                                + "        overlay.hide();\n"
                                + "        trigger.removeClass('is-open');\n"
                                + "        trigger.addClass('is-closed');\n"
                                + "        isClosed = false;\n"
                                + "      } else {   \n"
                                + "        overlay.show();\n"
                                + "        trigger.removeClass('is-closed');\n"
                                + "        trigger.addClass('is-open');\n"
                                + "        isClosed = true;\n"
                                + "      }\n"
                                + "  }\n"
                                + "  \n"
                                + "  $('[data-toggle=\"offcanvas\"]').click(function () {\n"
                                + "        $('#wrapper').toggleClass('toggled');\n"
                                + "  });  \n"
                                + "});\n"
                                + "</script>\n"
                                + "\n"
                                + "</body>\n"
                                + "</html>");
                    } finally {
                        out.close();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(_home_admin.class.getName()).log(Level.SEVERE, null, ex);
                    String pesan_error = ex.getMessage();
                    out.println("<!DOCTYPE html>\n"
                            + "<html lang=\"en\" >\n"
                            + "<head>\n"
                            + "  <meta charset=\"UTF-8\">\n"
                            + "  <title>Error 500 alert - #CodePenChallenges</title>\n"
                            + "  <link href=\"https://fonts.googleapis.com/css?family=Inconsolata:400,700\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css\">\n"
                            + "<style type=\"text/css\">\n"
                            + "html,\n"
                            + "body {\n"
                            + "  height: 100%;\n"
                            + "}\n"
                            + "body {\n"
                            + "  display: grid;\n"
                            + "  width: 100%;\n"
                            + "  font-family: Inconsolata, monospace;\n"
                            + "}\n"
                            + "body div#error {\n"
                            + "  position: relative;\n"
                            + "  margin: auto;\n"
                            + "  padding: 20px;\n"
                            + "  z-index: 2;\n"
                            + "}\n"
                            + "body div#error div#box {\n"
                            + "  position: absolute;\n"
                            + "  top: 0;\n"
                            + "  left: 0;\n"
                            + "  width: 100%;\n"
                            + "  height: 100%;\n"
                            + "  border: 1px solid #000;\n"
                            + "}\n"
                            + "body div#error div#box:before,\n"
                            + "body div#error div#box:after {\n"
                            + "  content: '';\n"
                            + "  position: absolute;\n"
                            + "  top: 0;\n"
                            + "  left: 0;\n"
                            + "  width: 100%;\n"
                            + "  height: 100%;\n"
                            + "  box-shadow: inset 0px 0px 0px 1px #000;\n"
                            + "  mix-blend-mode: multiply;\n"
                            + "  animation: dance 2s infinite steps(1);\n"
                            + "}\n"
                            + "body div#error div#box:before {\n"
                            + "  clip-path: polygon(0 0, 65% 0, 35% 100%, 0 100%);\n"
                            + "  box-shadow: inset 0px 0px 0px 1px currentColor;\n"
                            + "  color: #f0f;\n"
                            + "}\n"
                            + "body div#error div#box:after {\n"
                            + "  clip-path: polygon(65% 0, 100% 0, 100% 100%, 35% 100%);\n"
                            + "  animation-duration: 0.5s;\n"
                            + "  animation-direction: alternate;\n"
                            + "  box-shadow: inset 0px 0px 0px 1px currentColor;\n"
                            + "  color: #0ff;\n"
                            + "}\n"
                            + "body div#error h3 {\n"
                            + "  position: relative;\n"
                            + "  font-size: 5vw;\n"
                            + "  font-weight: 700;\n"
                            + "  text-transform: uppercase;\n"
                            + "  animation: blink 1.3s infinite steps(1);\n"
                            + "}\n"
                            + "body div#error h3:before,\n"
                            + "body div#error h3:after {\n"
                            + "  content: 'ERROR 500';\n"
                            + "  position: absolute;\n"
                            + "  top: -1px;\n"
                            + "  left: 0;\n"
                            + "  mix-blend-mode: soft-light;\n"
                            + "  animation: dance 2s infinite steps(2);\n"
                            + "}\n"
                            + "body div#error h3:before {\n"
                            + "  clip-path: polygon(0 0, 100% 0, 100% 50%, 0 50%);\n"
                            + "  color: #f0f;\n"
                            + "  animation: shiftright 2s steps(2) infinite;\n"
                            + "}\n"
                            + "body div#error h3:after {\n"
                            + "  clip-path: polygon(0 100%, 100% 100%, 100% 50%, 0 50%);\n"
                            + "  color: #0ff;\n"
                            + "  animation: shiftleft 2s steps(2) infinite;\n"
                            + "}\n"
                            + "body div#error p {\n"
                            + "  position: relative;\n"
                            + "  margin-bottom: 8px;\n"
                            + "}\n"
                            + "body div#error p span {\n"
                            + "  position: relative;\n"
                            + "  display: inline-block;\n"
                            + "  font-weight: bold;\n"
                            + "  color: #000;\n"
                            + "  animation: blink 3s steps(1) infinite;\n"
                            + "}\n"
                            + "body div#error p span:before,\n"
                            + "body div#error p span:after {\n"
                            + "  content: '}{|@#%_!';\n"
                            + "  position: absolute;\n"
                            + "  top: -1px;\n"
                            + "  left: 0;\n"
                            + "  mix-blend-mode: multiply;\n"
                            + "}\n"
                            + "body div#error p span:before {\n"
                            + "  clip-path: polygon(0 0, 100% 0, 100% 50%, 0 50%);\n"
                            + "  color: #f0f;\n"
                            + "  animation: shiftright 1.5s steps(2) infinite;\n"
                            + "}\n"
                            + "body div#error p span:after {\n"
                            + "  clip-path: polygon(0 100%, 100% 100%, 100% 50%, 0 50%);\n"
                            + "  color: #0ff;\n"
                            + "  animation: shiftleft 1.7s steps(2) infinite;\n"
                            + "}\n"
                            + "@-moz-keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes dance {\n"
                            + "  0%, 84%, 94% {\n"
                            + "    transform: skew(0deg);\n"
                            + "  }\n"
                            + "  85% {\n"
                            + "    transform: skew(5deg);\n"
                            + "  }\n"
                            + "  90% {\n"
                            + "    transform: skew(-5deg);\n"
                            + "  }\n"
                            + "  98% {\n"
                            + "    transform: skew(3deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-moz-keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes shiftleft {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(-8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-moz-keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes shiftright {\n"
                            + "  0%, 87%, 100% {\n"
                            + "    transform: translate(0, 0) skew(0deg);\n"
                            + "  }\n"
                            + "  84%, 90% {\n"
                            + "    transform: translate(8px, 0) skew(20deg);\n"
                            + "  }\n"
                            + "}\n"
                            + "@-moz-keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "@-webkit-keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "@-o-keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "@keyframes blink {\n"
                            + "  0%, 50%, 85%, 100% {\n"
                            + "    color: #000;\n"
                            + "  }\n"
                            + "  87%, 95% {\n"
                            + "    color: transparent;\n"
                            + "  }\n"
                            + "}\n"
                            + "</style>\n"
                            + "\n"
                            + "</head>\n"
                            + "<body>\n"
                            + "<!-- partial:index.partial.html -->\n"
                            + "<div id=\"error\">\n"
                            + "  <div id=\"box\"></div>\n"
                            + "  <h3>ERROR 500</h3>\n"
                            + "  <p>Inter<span>nal Serv</span>er <span>Err0r*=@#!</span>234Z_</p>\n"
                            + "  <p>" + pesan_error + "</p>\n"
                            + "</div>\n"
                            + "<!-- partial -->\n"
                            + "  \n"
                            + "</body>\n"
                            + "</html>");
                }
            } else {
                PrintWriter output = response.getWriter();
                output.println("<script type=\"text/javascript\">");
                output.println("alert('BUKAN HAK KAU!');");
                output.println("location='./halaman_login/index.html';");
                output.println("</script>");
                output.close();
            }

        } else {
            response.sendRedirect("./index.html");
        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
